spring.application.name=e-commerce

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=never
server.error.include-binding-errors=never


stripe.secret-key=sk_test_51TPk9QQAjnHlHwUF4eYt6bg04bZXM7Epr03XsaApppllTQ38iPpRiSmpmUrDfdSe9tbC0HpPX6Cof4Df20plZ9da00NLPr9bGy
stripe.webhook.secret=whsec_1fc8add6ee91d63c4eb5f8559dc01427ff1386ec68b5cf4148bed04be28d8e66
abacate-pay.secret-key=abc_dev_frMErEJzyhGHzqXcBLhZDggK
abacate-pay.webhook.secret=webh_dev_BeEZrtGsJM6D1uABusRBYz51

jwt.secret=and0c2VjcmV0LWUtY29tbWVyY2UtYXBp