spring.application.name=e-commerce

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=never
server.error.include-binding-errors=never


stripe.secret-key=${STRIPE_KEY}
stripe.webhook.secret=${WEBHOOK_SECRET}
abacate-pay.secret-key=${ABACATE_PAY_KEY}
abacate-pay.webhook.secret=${ABACATE_PAY_WEBHOOK_SECRET}

jwt.secret=${JWT_SECRET}