CREATE TABLE order_items (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

                             order_id UUID NOT NULL,
                             product_id UUID NOT NULL,

                             quantity INTEGER NOT NULL,
                             unit_price NUMERIC(10,2) NOT NULL,

                             FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                             FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order ON order_items(order_id);