ALTER TABLE orders ADD COLUMN payment_id UUID;
ALTER TABLE orders ADD CONSTRAINT fk_payment FOREIGN KEY (payment_id) REFERENCES payments(id);

ALTER TABLE orders ADD COLUMN payment_status_snapshot VARCHAR(30);

ALTER TABLE orders ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE orders ADD COLUMN paid_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN shipped_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE orders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

