CREATE TABLE users (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(100) not null unique,
                          email varchar(100) not null unique,
                          password varchar(100) not null,
                          enable BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at VARCHAR(100) NOT NULL UNIQUE,
                          updated_at VARCHAR(30)
);